openapi: 3.0.1
info:
  title: Strive-Blog
  version: "1"
  description: All the endpoints dedicated to blog posts
paths:
  /posts:
    summary: Endpoints for operations on books
    get:
      summary: Retrieve all the posts
      description: ""
      operationId: ""
      responses:
        "200":
          description: Ok response
          content:
            application/json:
              examples:
                Ok response:
                  value: |-
                    {
                    }
        "400":
          description: Default error sample response
          content:
            application/json:
              examples:
                Ok response:
                  value: |-
                    {
                    }
      tags:
        - posts
    post:
      summary: Creates a new book
      description: ""
      operationId: ""
      responses:
        default:
          description: Default error sample response
      tags:
        - posts
  /books/{bookId}:
    get:
      summary: Get a book by ID
      parameters:
        - in: path
          name: bookId
          schema:
            type: integer
          required: true
          description: Numeric ID of the book to get
      responses:
        "200":
          description: Ok response
          content:
            application/json:
              examples:
                Ok response:
                  value: |-
                    {
                    }
        "400":
          description: Default error sample response
          content:
            application/json:
              examples:
                Ok response:
                  value: |-
                    {
                    }
      tags:
        - posts
    put:
      summary: ""
      parameters:
        - in: path
          name: postsId
          schema:
            type: integer
          required: true
          description: Numeric ID of the book to get
      description: ""
      operationId: ""
      responses:
        default:
          description: Default error sample response
      tags:
        - posts
    delete:
      summary: ""
      parameters:
        - in: path
          name: bookId
          schema:
            type: integer
          required: true
          description: Numeric ID of the book to get
      description: ""
      operationId: ""
      responses:
        default:
          description: Default error sample response
      tags:
        - posts
servers:
  - url: http://localhost:3001
    variables: {}
    description: Local Server
  - url: https://myremoteserver.herokuapp.com
    variables: {}
    description: Remote sever
# https://editor.swagger.io/?_ga=2.147054271.941794559.1635460478-964777229.1635460478
